development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pioneer_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pioneer_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
